### ISSUE TITLE
training manner?  two-stage or end2end 

### ISSUE THREAD

**Issue by Oran-Ac** [jokieleung/NTRD#1]
Hi there,
thanks for your fantastic work. However, I am a little confused about the differences between the readme.md and your paper.
In your paper,
you mentioned in Section 4.3 that 
> Though the entire framework is typically two-stage, the two modules can be trained simultaneously in an end-to-end manner.

but you use ` python run.py` in readme.md which is obvious a two-stage training manner.

So should we use `python  e2e_run.py` for end2end training or `python run.py` for two- stage training in order to reproduce your results?
Thx.

**Comment by jokieleung** [comment]
Hi, thanks for your following. The claim in Section 4.3 means that the "template generation" and "slot filling" processes can be trained simultaneously in an end-to-end manner. Both of these 2 processes are included in the dialogue generation task.

On the other hand, the command ```python run.py``` is first to pre-train the recommender module. And the following command ```python run.py --is_finetune True``` is to train the dialogue generation task.

We have also explored that training the recommender module and the dialogue generation task in an e2e manner by running ```python e2e_run.py```, but the performance seems to be not as good as the pre-training recommender module first, which is also the implementation of KGSF. So the script ```e2e_run.py``` is not related to the experiments mentioned in the paper, you can just ignore it.

**Comment by Oran-Ac** [comment]
thanks so much for your kindly help. We have made your model available in our toolkit 😄 [CRSLab](https://github.com/RUCAIBox/CRSLab/pull/33)

**Comment by jokieleung** [comment]
Cool! Fantastic work!
