### ISSUE TITLE
run_novel vs run vs e2e

### ISSUE THREAD

**Issue by dayuyang1999** [jokieleung/NTRD#6]
Hi,

Thank you for your contribution. It is a great work!

Could you please explain the logic behind the file names? What is the difference between run.py, run_novel.py, and e2e_run.py?
And what is the difference between the model file behind them: e2e_model, model, and model_novel. 

Those three names are kind of confusing. Thanks!

**Comment by jokieleung** [comment]
Hi, 

Thanks for your following! Regarding the difference between `run.py` and `e2e_run.py` , I have made some explanations here -> https://github.com/jokieleung/NTRD/issues/1#issuecomment-943135251 
As for the `run_novel.py`, it is for the experiments mentioned in Section 6.2 of our paper. 
Hope it can help you.
