### ISSUE TITLE
Should I change the arg '-infomax_pretrain' to True?

### ISSUE THREAD

**Issue by xansar** [jokieleung/NTRD#7]
I found that there is a part of codes about informax_pretraining,  but due to the arg '-infomax_pretrain' is False, this part will not be executed. If I want to reproduce the test results in the paper, should I change the arg '-infomax_pretrain' to True?

**Comment by xansar** [comment]
This part of codes is in TrainLoop_fusion_rec class. Thank you!

**Comment by dayuyang1999** [comment]
> TrainLoop_fusion_rec

Did you find out why? I found it to be weird as well.

**Comment by xansar** [comment]
> > TrainLoop_fusion_rec
> 
> Did you find out why? I found it to be weird as well.

Sorry, I have not found any reason for the weird results.

**Comment by dayuyang1999** [comment]
> > > TrainLoop_fusion_rec
> > 
> > 
> > Did you find out why? I found it to be weird as well.
> 
> Sorry, I have not found any reason for the weird results.

Not yet.

**Comment by dayuyang1999** [comment]
> > > TrainLoop_fusion_rec
> > 
> > 
> > Did you find out why? I found it to be weird as well.
> 
> Sorry, I have not found any reason for the weird results.

BTW, do you know why NTRD and KGSF both commented info_con_loss?  I think this leads to the issue that the embedding of conceptNet is not trained.

**Comment by xansar** [comment]
> > > > TrainLoop_fusion_rec
> > > 
> > > 
> > > Did you find out why? I found it to be weird as well.
> > 
> > 
> > Sorry, I have not found any reason for the weird results.
> 
> BTW, do you know why NTRD and KGSF both commented info_con_loss? I think this leads to the issue that the embedding of conceptNet is not trained.

Sorry, I didn't pay attention to info_con_loss. Because when I trained KGSF, the model performed well with info_con_loss commented. I will try to retrain the model in your way, and if you have some progress in this problem, please inform me. Thank you!

**Comment by dayuyang1999** [comment]
> 

Hi,

After I check the code, I think the purpose of info_db_loss is trying to "making the conceptnet(KG2) item to be able to predict dbpedia(KG1) items". 

So I think the authors of KGSF first tried to predict KG1 given KG2 (info_db_loss), and then tried something in the opposite direction(info_con_loss), and find out the 2nd direction is not helpful to improve model performance(may harm). So they commented info_con_loss.

BTW, can I add your WeChat? If it is ok, would you mind to send your wechat number to my email address? dylanyang@smail.nju.edu.cn.

**Comment by jokieleung** [comment]
Yes. -infomax_pretrain should be set to True.
