### ISSUE TITLE
how to reach the performance NTRD should have?

### ISSUE THREAD

**Issue by dayuyang1999** [jokieleung/NTRD#9]
Hi Jokie,

After I fixed the bug, now I can run your code smoothly. However, I found I am unable to replicate the claimed performance that is shown on the paper. Could you please help me?

The parameter setting follows the paper:
- infomax pretain = True
- for rec task, epoch = 30
- for sentence generation task, epoch = 30*3

I did not change any other thing and I got the results of rec task as:
'recall@1': 0.01972770213948319, 
'recall@10': 0.2856348985829397, 
'recall@50': 0.7265907196443456}

This is much lower than the paper claims! I did not know which step I messed up.

After I fine-tuning on sentence generation task, I got the results as:
{'ppl': 4.646927499761735, 

'dist1': 0.07012840412022012, 
'dist2': 0.31649499082827715, 
'dist3': 0.4667701425144631, 
'dist4': 0.5724566106956399, 

'bleu1': 0.093541870702522,
 'bleu2': 0.026171342178387604,
 'bleu3': 0.016242155418590167, 
'bleu4': 0.011014523340149043, }

=================================================
I ran the code 3 times, results are similar. Here is the comparison of results after taking the average:

![image](https://user-images.githubusercontent.com/60718476/163865749-9624127e-ef88-4fa6-9201-0b1d5a7ec643.png)

what I can observe is that rec performance is a little lower than KGSF, and sentence task is better than KGSF(but not reach the claimed performance).

I think the result does not make sense since I think the method purposed on the paper is certainly better than KGSF, which take the actual movie name into account.

**Comment by Yang-bug-star** [comment]
Hi, did you solve the problem? I ran KGSF and found that the dist metric is twice larger than that in original paper, is it normal? And also I didn't quite know the meaning of ReR in NTRD and found its corresponding implementation confusing.
